[package]
name = "complexity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = "1.0"
serde-pickle = "1.0"
savefile = "0.10.1"
fstrings = "0.2.3"